runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /.well-known
  static_dir: well-known

- url: /.*
  script: api.app
  secure: always

automatic_scaling:
  max_idle_instances: 10

env_variables:
  GCLOUD_PROJECT: 'willys-4fbc0'
