runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /
  script: src.home.main.app

- url: /.well-known
  static_dir: well-known

- url: /.*
  script: src.helpers.generic_errors.main.app

automatic_scaling:
  max_idle_instances: 10
