runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /
  script: services.default.home.index.app

- url: /.well-known
  static_dir: well-known

- url: /.*
  script: helpers.generic_errors.router.app
